### ISSUE TITLE
UnknownPropertyException NetName: unknown property when subscribig to DB events

### ISSUE THREAD

**Issue by jvmlet** [microsoft/sqlmanagementobjects#118]
I'm getting the `UnknownPropertyException NetName: unknown property.`  when trying to  subscribe to DB events :

````c#
database.Events.SubscribeToEvents(new DatabaseEventSet(DatabaseEvent.CreateTable), (s, e) => { });
````

DB Server is `Synapse`, `<PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="170.8.0" />` 

````
Microsoft.SqlServer.Management.Smo.UnknownPropertyException
NetName: unknown property.
   at Microsoft.SqlServer.Management.Smo.SqlPropertyMetadataProvider.PropertyNameToIDLookupWithException(String propertyName, PropertyAccessPurpose pap)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.LookupID(String propertyName, PropertyAccessPurpose pap)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName, Boolean throwOnNullValue, Boolean useDefaultOnMissingValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName)
   at Microsoft.SqlServer.Management.Smo.Information.get_NetName()
   at Microsoft.SqlServer.Management.Smo.ServerEvents.get_ManagementScope()
   at Microsoft.SqlServer.Management.Smo.EventsWorkerBase..ctor(SqlSmoObject target, Type eventSetType, Type eventEnumType)
   at Microsoft.SqlServer.Management.Smo.DatabaseEventsWorker..ctor(Database target)
   at Microsoft.SqlServer.Management.Smo.DatabaseEvents.InitializeEvents()
   at Microsoft.SqlServer.Management.Smo.DatabaseEvents.SubscribeToEvents(DatabaseEventSet events, ServerEventHandler eventHandler)
````

**Comment by shueybubbles** [comment]
I think these events are only meant to work for on-premises editions of SQL Server not for cloud. 
`ManagementScope` is a Windows Management concept.
We can try to make at least part of these events work for cloud but I don't know when that work would happen.

**Comment by jvmlet** [comment]
@shueybubbles , the documentation [clearly  states](https://learn.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/create-program/handling-smo-events?view=azure-sqldw-latest) that SMO is applicable to `Azure Synapse Analytics` as well.

**Comment by shueybubbles** [comment]
I appreciate that SMO supports many versions of SQL, but not all SMO functionality is equally applicable to every version of SQL. There are quite a few box-only subsystems like WMI and SQL Agent that have SMO objects to support them.

These particular event monitoring classes are implemented using Windows Management Instrumentation which is not available for cloud services.
See https://github.com/microsoft/sqlmanagementobjects/blob/98093604e9ede97aa2a9b066279f0bd9d9557c4f/src/Microsoft/SqlServer/Management/Smo/ServerEventsWorker.cs#L519 where it builds the WQL queries for fetching information from WMI.
