### ISSUE TITLE
Missing method when using SQLClient 5.0.1

### ISSUE THREAD

**Issue by acomarce** [microsoft/sqlmanagementobjects#124]
The following issue occurs when using `v161.46521.71` with SQLClient `5.0.1`: 

```
System.MissingMethodException: Method not found: 'Void Microsoft.Data.SqlClient.SqlConnectionStringBuilder.set_Encrypt(Boolean)'.
   at Microsoft.SqlServer.Management.Common.ConnectionSettings.GetConnectionString()
   at Microsoft.SqlServer.Management.Common.ConnectionSettings.get_ConnectionString()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InitSqlConnectionObject(Boolean setConnectionString, Boolean removeIntegratedSecurity)
   at Microsoft.SqlServer.Management.Common.ConnectionManager..ctor(IRenewableToken token, Boolean removeIntegratedSecurity)
   at Microsoft.SqlServer.Management.Common.ConnectionManager..ctor()
   at Microsoft.SqlServer.Management.Common.ServerConnection..ctor(String serverInstance)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ConnectionFactory.CreateServerConnection(String connString, String initialCatalog, Boolean poolConn, IRenewableToken accessToken)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ConnectionFactory.GetDatabaseConnection(String dbName, Boolean poolConnection, IRenewableToken accessToken)
   at Microsoft.SqlServer.Management.Common.ServerConnection.GetDatabaseConnection(String dbName, Boolean poolConnection)
   at Microsoft.SqlServer.Management.Smo.Database.get_DatabaseExecutionManager()
   at Microsoft.SqlServer.Management.Smo.Database.get_ExecutionManager()
   at Microsoft.SqlServer.Management.Smo.Database.get_DatabaseEngineEdition()
   at Microsoft.SqlServer.Management.Smo.Database.GetPropertyMetadataProvider()
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.get_Properties()
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AddObjectPropsFromDataReader(IDataReader reader, Boolean skipIfDirty, Int32 startColIdx, Int32 endColIdx)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AddObjectPropsFromDataReader(IDataReader reader, Boolean skipIfDirty)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.Microsoft.SqlServer.Management.Sdk.Sfc.ISqlSmoObjectInitialize.InitializeFromDataReader(IDataReader reader)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.CreateNewObjectFromRow(AbstractCollectionBase childColl, Type childType, IDataReader reader, Int32 columnIdx, Boolean isOrderedByID, Boolean skipOrderChecking)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitObjectsFromEnumResultsRec(SqlSmoObject currentSmoObject, XPathExpression levelFilter, Int32 filterIdx, IDataReader reader, Int32 columnIdx, Object[] parentRow, Boolean forScripting, List`1 urnList, Int32 startLeafIdx)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitObjectsFromEnumResults(Urn levelFilter, IDataReader reader, Boolean forScripting, List`1 urnList, Int32 startLeafIdx, Boolean skipServer)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.Refresh(Boolean refreshChildObjects)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.Refresh()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\a.m\RiderProjects\ConsoleApp2\ConsoleApp2\Program.cs:line 22
```

For more details see [here](https://github.com/dotnet/SqlClient/issues/1875#issuecomment-1377810979).

**Comment by shueybubbles** [comment]
You need to use a v170 SMO release to use SQLClient 5.
