### ISSUE TITLE
Microsoft.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by wsmelton** [microsoft/sqlmanagementobjects#149]
I've searched this repository along with the sqlclient repository. There are multiple issues bring this up but are either closed or solutions provided don't seem to fix the issue I'm getting.

I'm trying to create a basic binary module in PowerShell against SQL Server. I have a basic project structure with just one cmdlet so far (trying to see if this even works) that references SMO library.

Project: https://github.com/wsmelton/dbalight/tree/modulebuilder/source/dbalight

The project compiles for dotnet 6 on my M1 and the module imports with no issues. It is not until I call the `Connect-DblServer`:

```console
Exception             : 
    Type       : System.PlatformNotSupportedException
    TargetSite : Void .ctor()
    Message    : Microsoft.Data.SqlClient is not supported on this platform.
    Source     : Microsoft.Data.SqlClient
    HResult    : -2146233031
    StackTrace : 
   at Microsoft.Data.SqlClient.SqlConnection..ctor()
   at Microsoft.SqlServer.Management.Common.ConnectionManager..ctor(IRenewableToken token, Boolean removeIntegratedSecurity)
   at Microsoft.SqlServer.Management.Common.ConnectionManager..ctor()
   at Microsoft.SqlServer.Management.Common.ServerConnection..ctor()
   at dbalight.cmdlets.general.ConnectServerCmdlet.ProcessRecord() in 
/Users/smelton/git/dbalight/source/dbalight/cmdlets/public/ConnectServer.cs:line 41
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Connect-DblServer], PlatformNotSupportedException
FullyQualifiedErrorId : System.PlatformNotSupportedException,dbalight.cmdlets.general.ConnectServerCmdlet
InvocationInfo        : 
    MyCommand        : Connect-DblDblServer
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 26
    Line             : Connect-DblServer -ServerInstance 'localhost,1432' -Verbose
    PositionMessage  : At line:1 char:1
                       + Connect-DblServer -ServerInstance 'localhost,1432' -Verbose
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Connect-DblServer
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

Line 41 of that cs file for the cmdlet is: `ServerConnection srvCn = new ServerConnection();`

- Is there something in my csproj that I have configured wrong?
- Is this just broken and I need to revert to an older version of the SQLManagementObjects library?

**Comment by shueybubbles** [comment]
is your deployment somehow copying the file from `lib` instead of from `runtimes` ?

**Comment by DavoudEshtehari** [comment]
I tried to compile and use the sample project on ARM supported machine and I got the platform not supported exception on PS7. Then I tried locally on Windows 11 and x64, which didn't change the result. Can you share the commands and instructions if you could run it on a x64 supported machine and it's only an ARM related issue?
![image](https://github.com/microsoft/sqlmanagementobjects/assets/61173489/476134ae-89b4-491e-8058-594005d7bbc4)

**Comment by wsmelton** [comment]
```posh
git clone https://github.com/wsmelton/dbalight.git
Install-Module ModuleBuilder # or Install-PSResource ModuleBuilder
./build.ps1 -Verbose
```

@DavoudEshtehari run the above in PowerShell 7.2+ should get it going.

I don't have access to any Windows device, only on a Apple Mac M1:

<img width="215" alt="image" src="https://github.com/microsoft/sqlmanagementobjects/assets/11204251/02a27bab-af41-431e-bcfa-de10a05bc441">

@shueybubbles on the build process I'm only running `dotnet build -c Release` so it creates in `bin/net6.0/osx.12-arm64`. The module build I'm copying that path up to the module's directory (minus the osx folder reference).

**Comment by wsmelton** [comment]
I don't have Windows nor do I use it so unsure what additional requirements there would be to get the build of the project to run succesful.

**Comment by wsmelton** [comment]
@DavoudEshtehari that error comes from two things:

1. You don't have the `dotnet-gitversion` installed on your machine
2. You downloaded the zip of the project and didn't clone it. Cloning is required for `gitversion` to be used (it requires the git database for the project to be on your local device)

**Comment by wsmelton** [comment]
If I use either SMO for `netstandard2.0` or `net6.0` neither one seems to work on Mac. 

I have 6 and 7 SDK installed on the device:

<img width="1283" alt="image" src="https://github.com/microsoft/sqlmanagementobjects/assets/11204251/e5e8a11b-09f4-479b-835d-9d71b7929900">

**Comment by DavoudEshtehari** [comment]
@wsmelton Thanks, `dotnet-gitversion` was required and I confirm the build ran successfully either on x64 or ARM64 Win 11 machines, but the result is identical after running the following commands:
> Import-Module ...Output\dbalight\0.1.0\dbalight.dll
> Connect-Server

 `Connect-Server: Microsoft.Data.SqlClient is not supported on this platform.`

**Comment by shueybubbles** [comment]
@DavoudEshtehari should this issue move over to dotnet/sqlclient?

**Comment by DavoudEshtehari** [comment]
I don't have permission to move it into SqlClient. I'd appreciate it if you could do it.

**Comment by shueybubbles** [comment]
you'd have to open a new one then we can close this one with a link to it. Moving issues only works within the same organization.
