### ISSUE TITLE
Go utility statement incorrectly processed

### ISSUE THREAD

**Issue by dudeNumber4** [microsoft/sqlmanagementobjects#53]
Using latest version (161.46367.54) I'm getting errors processing `go`.  Usage of the statement is proper according to [this doc](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-ver15).
I've narrowed the problem down to the 2 simplest sql statements below.  Both statements work in SSMS.  Using SMO, both are called this way:

```
using Microsoft.Data.SqlClient;
using Microsoft.SqlServer.Management.Common;
using Microsoft.SqlServer.Management.Smo;

using var con = new SqlConnection("Server=.\\SQLExpress;Database=my_db;Integrated Security=true");
var serverConnection = new Server(new ServerConnection(con));
var sql = $"select 1{Environment.NewLine}go";   // actual use case is file originally created in SSMS
using SqlDataReader result = serverConnection.ConnectionContext.ExecuteReader(sql);
```

Works properly:
```
select 1
go
```

Error: _Incorrect syntax near 'go'_
```
create table x(id int)
go
```

I can debug into assembly MS.SqlServer.ConnectionInfo, but no matter what I try (why is this so hard?) I can't step into other dependent assemblies.  In both above cases, I get to ConnectionManager.cs.ExecuteTSql, `switch (action) -> ExecuteReader`.  At that point, the failing statement crashes, the passing statement goes into ServerConnection.GetExecuteReader.

**Comment by shueybubbles** [comment]
"GO" is purely a UI convenience, as that document you referred to states. SSMS breaks up the typed-in text into batches based on the GO as a delimiter; it doesn't send "GO" to the server at all.

**Comment by dudeNumber4** [comment]
I've been using SMO to process TSQL containing 'go' for quite some time.

**Comment by dudeNumber4** [comment]
I've been successfully processing statements (authored in SSMS) with `go` for a long time.  For proof, put this query into code snippet above:
`select 1
go 
select 2`
The first reader will contain 1, advancing to the next reader using `result.NextResult();` will return 2.

**Comment by shueybubbles** [comment]
I'm not sure what I can do about this. AFAIK the only methods in SMO that parse batches are `Database.ExecuteNonQuery` and [ServerConnection.ExecuteNonQuery](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.common.serverconnection.executenonquery?view=sql-smo-160)

The `ExecuteReader` is a straight pass-through to `SqlCommand.ExecuteReader`. 
I assume using ExecuteNonQuery is more useful for "create table" commands, too.

If I remove SMO from the repro, I see both System.Data.SqlConnection.SqlCommand and Microsoft.Data.SqlConnection.SqlCommand show the same error.
This is the code:

```C#
using System;
using SDS = System.Data.SqlClient;
using MDS = Microsoft.Data.SqlClient;
namespace SqlCommandBatch
{
    class Program
    {
        static void Main(string[] args)
        {
            var server = args.Length > 0 ? args[0] : ".";
            using (var conn = new SDS.SqlConnection($"Data Source={server};Integrated Security=true;Pooling=false"))
            {
                conn.Open();
                var command = conn.CreateCommand();
                command.CommandText = $"Create Database db3";
                command.ExecuteNonQuery();
                conn.ChangeDatabase("db3");
                command.CommandText = $"Create Table x (col1 int){Environment.NewLine}GO{Environment.NewLine}";
                try
                {
                    var reader = command.ExecuteReader();
                    Console.WriteLine($"SDS reader.HasRows: {reader.HasRows}");
                }
                catch (Exception e)
                {
                    Console.WriteLine($"System.Data.SqlClient.SqlCommand.ExecuteReader threw {e}");
                }
            }

            using (var conn = new MDS.SqlConnection($"Data Source={server};Integrated Security=true;Pooling=false"))
            {
                conn.Open();
                var command = conn.CreateCommand();
                conn.ChangeDatabase("db3");
                command.CommandText = $"Create Table y (col1 int){Environment.NewLine}GO{Environment.NewLine}";
                try
                {
                    var reader = command.ExecuteReader();
                    Console.WriteLine($"MDS reader.HasRows: {reader.HasRows}");
                }
                catch (Exception e)
                {
                    Console.WriteLine($"Microsoft.Data.SqlClient.SqlCommand.ExecuteReader threw {e}");
                }
                conn.ChangeDatabase("master");
                command.CommandText = $"drop database db3";
                command.ExecuteNonQuery();
            }

            Console.ReadKey();
        }
    }
}

```

And this is the error:

```
System.Data.SqlClient.SqlCommand.ExecuteReader threw System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'GO'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at SqlCommandBatch.Program.Main(String[] args) in f:\src\SqlCommandBatch\Program.cs:line 21
ClientConnectionId:1c12769d-091c-45b5-95e2-83872e0e347e
Error Number:102,State:1,Class:15
Microsoft.Data.SqlClient.SqlCommand.ExecuteReader threw Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'GO'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 2287
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlInternalConnection.cs:line 773
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParser.cs:line 1677
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParser.cs:line 2904
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData() in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlDataReader.cs:line 1333
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData() in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlDataReader.cs:line 283
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 5645
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 5411
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4995
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 4845
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 2448
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader() in H:\tsaagent1\_work\46\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 2365
   at SqlCommandBatch.Program.Main(String[] args) in f:\src\SqlCommandBatch\Program.cs:line 38
ClientConnectionId:e34e0bf0-93eb-4e48-820a-5eb813b80c07
Error Number:102,State:1,Class:15
```

**Comment by dudeNumber4** [comment]
I'm not sure what you're communicating above.  "_If I remove SMO from the repro_."  SMO is the issue at hand.  Isn't one of the use cases for SMO to run statements containing `go`?

**Comment by shueybubbles** [comment]
The only code in SMO that explicitly parses batches is ExecuteNonQuery. All other Executexxx functions are passed straight through to  the SqlCommand equivalent. I don't know why some of those SqlCommand equivalents work sometimes and not others.

**Comment by dudeNumber4** [comment]
Above you say that only ExecuteNonQuery parses batches.  Not so.  I mentioned above that if you alter the original snippet, it will parse 'go' with ExecuteReader.  Here is full snippet:

```
using System.Data;
using Microsoft.Data.SqlClient;
using Microsoft.SqlServer.Management.Common;
using Microsoft.SqlServer.Management.Smo;
using System;

var connectionBuilder = new SqlConnectionStringBuilder(@"Server=.\SQLEXPRESS;Integrated Security=true;Initial Catalog=Sandbox");
using var con = new SqlConnection(connectionBuilder.ConnectionString);
var serverConnection = new Server(new ServerConnection(con));

var sql = $"select 1{Environment.NewLine}go{Environment.NewLine}select 2";
using SqlDataReader result = serverConnection.ConnectionContext.ExecuteReader(sql);
result.Read();
Console.WriteLine($"First result: {result[0]}");
result.NextResult();
result.Read();
Console.WriteLine($"Second result: {result[0]}");

```

**Comment by shueybubbles** [comment]
It's not working because SMO is parsing the batches. It's working because somehow SqlCommand.ExecuteReader is doing something intelligent with it. I don't know why it works for that statement but not for create table.

```C#
using System;
using SDS = System.Data.SqlClient;
namespace SqlCommandBatch
{
    class Program
    {
        static void Main(string[] args)
        {
            var server = args.Length > 0 ? args[0] : ".";
            using (var conn = new SDS.SqlConnection($"Data Source={server};Integrated Security=true;Pooling=false"))
            {
                conn.Open();
                var command = conn.CreateCommand();
                command.CommandText = $"Create Database db6";
                command.ExecuteNonQuery();
                conn.ChangeDatabase("db6");
                command.CommandText = $"select 1{Environment.NewLine}go{Environment.NewLine}select 2";
                try
                {
                    using (var reader = command.ExecuteReader())
                    {
                        Console.WriteLine($"SDS reader.HasRows: {reader.HasRows}");
                        reader.Read();
                        Console.WriteLine($"First result: {reader[0]}");
                        reader.NextResult();
                        reader.Read();
                        Console.WriteLine($"Second result: {reader[0]}");
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine($"System.Data.SqlClient.SqlCommand.ExecuteReader threw {e} for 2 selects");
                }
                command.CommandText = $"Create Table y (col1 int){Environment.NewLine}GO{Environment.NewLine}";
                try
                {
                    command.ExecuteReader();
                }
                catch (Exception e)
                {
                    Console.WriteLine($"System.Data.SqlClient.SqlCommand.ExecuteReader threw {e} for create table");
                }
            }

            Console.ReadKey();
        }
    }
}
```

Output:

```
SDS reader.HasRows: True
First result: 1
Second result: 2
System.Data.SqlClient.SqlCommand.ExecuteReader threw System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'GO'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at SqlCommandBatch.Program.Main(String[] args) in f:\src\SqlCommandBatch\Program.cs:line 39
ClientConnectionId:a8516309-3b3c-41de-a3a4-a2b65d0b0138
Error Number:102,State:1,Class:15 for create table

```

**Comment by shueybubbles** [comment]
BTW I think your `select` example works because `select 1 go` is equivalent to `select 1 as go` and it's returning a 1 row table with a column named `go`
The key is that the ADO client treats new line characters the same as spaces, while SSMS treats a newline as a potential statement ender.

As you can see with SSMS if you leave the line feeds out it does the same thing.

![image](https://user-images.githubusercontent.com/2224906/126183834-1c4abe9b-cd31-43bc-8060-72a582b977f5.png)

If you terminate your desired statements with semi colons things get annoying.
The batch parser in SSMS only looks for `GO` on its own line so this is an error

![image](https://user-images.githubusercontent.com/2224906/126184080-a55f5f86-bb18-44e7-a491-a4c8eb59f304.png)

And putting the `GO` on its own line removes the column name

![image](https://user-images.githubusercontent.com/2224906/126184207-83f36099-f0df-43d8-b83f-bad14254a583.png)
