### ISSUE TITLE
Credential Scripting fails with Smo.Scripter

### ISSUE THREAD

**Issue by potatoqualitee** [microsoft/sqlmanagementobjects#58]
I have a couple Credentials that I cannot script.

It looks like this in SSMS

![image](https://user-images.githubusercontent.com/8278033/125444282-e60cf325-ffa5-4be5-869d-4785a4628fd0.png)

Sometimes I get this error

```
System.Management.Automation.MethodInvocationException: Exception calling "EnumScript" with "1" argument(s): "Script
failed for  'PowerShell Proxy'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Script failed for   'PowerShell Proxy'.  ---> System.NullReferenceException: Object reference not set to an instance of an object.         at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AddObjectPropsFromDataReader(IDataReader reader, Boolean        skipIfDirty, Int32 startColIdx, Int32 endColIdx)                                                                         at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitializeKeepDirtyValues()                                        at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptCreateObject(Urn urn, ScriptingPreferences sp,             ObjectScriptingType& scriptType)                                                                                         at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptCreate(Urn urn, ScriptingPreferences sp,                   ObjectScriptingType& scriptType)                                                                                         at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptCreateObjects(IEnumerable`1 urns)                             at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptUrns(List`1 orderedUrns)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.DiscoverOrderScript(IEnumerable`1 urns)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptWorker(List`1 urns, ISmoScriptWriter writer)
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithListWorker(DependencyCollection depList, SqlSmoObject[]
objects, Boolean discoveryRequired)
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(DependencyCollection depList, SqlSmoObject[]
objects, Boolean discoveryRequired)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(DependencyCollection depList, SqlSmoObject[]
objects, Boolean discoveryRequired)
   at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(Urn[] urns, SqlSmoObject[] objects)
   at Microsoft.SqlServer.Management.Smo.Scripter.Script(Urn[] urns, SqlSmoObject[] objects)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception
exception)
   at Export-DbaScript<Process>(Closure , FunctionContext )
```

Other times I get this error

```
xception             : System.Management.Automation.MethodInvocationException: Exception calling "EnumScript" with
                        "1" argument(s): "Script failed for  'PSPower'. " --->
                        Microsoft.SqlServer.Management.Smo.FailedOperationException: Script failed for  'PSPower'.
                        ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: Script failed.  --->
                        Microsoft.SqlServer.Management.Smo.SmoException: Cannot script the object with
                        Urn='Server[@Name='WORKSTATION']/Credential[@Name='PSPower']'.
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.ScriptMaker.VerifyInput(List`1 urns)
                           at Microsoft.SqlServer.Management.Smo.ScriptMaker.ScriptWorker(List`1 urns,
                        ISmoScriptWriter writer)
                           at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithListWorker(DependencyCollection
                        depList, SqlSmoObject[] objects, Boolean discoveryRequired)
                           at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(DependencyCollection
                        depList, SqlSmoObject[] objects, Boolean discoveryRequired)
                           --- End of inner exception stack trace ---
                           at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(DependencyCollection
                        depList, SqlSmoObject[] objects, Boolean discoveryRequired)
                           at Microsoft.SqlServer.Management.Smo.Scripter.ScriptWithList(Urn[] urns, SqlSmoObject[]
                        objects)
                           at Microsoft.SqlServer.Management.Smo.Scripter.Script(Urn[] urns, SqlSmoObject[] objects)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Ex
                        ception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                           at CallSite.Target(Closure , CallSite , Object , Object )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0,
                        T1 arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame
                        frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interprete
                        dFrame frame)
```

Here's how I can repro

```
$object = $server.Credentials | select -last 1
$scripter = New-Object Microsoft.SqlServer.Management.Smo.Scripter $server
$scripter.EnumScript($object)
```

I am using the latest version of SMO but I've seen this in older versions.

**Comment by shueybubbles** [comment]
Do you have a script for creating such a credential we can use to test?

**Comment by potatoqualitee** [comment]
No :( That one was created using SSMS a while back. I can pin down what is different about it. The account is still valid and works.

**Comment by potatoqualitee** [comment]
Awesome! Thank you 😍  Invaluable info.
